export type Material = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  metadata: null;
  companyId: string;
  name: string;
  sku: string;
  width: string;
  units: string;
  price: null;
  stockAvailable: boolean;
  materialType: MaterialType;
  materialTypeId: number;
  partnerSKU: null;
  partnerName: null;
  partner: null;
  partnerId: null;
};

export type MaterialType = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  metadata: null;
  deletedAt: null;
  name: string;
  description: string;
  units: string;
  inkType: null;
  inkTypeId: null;
};
export type Order = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  metadata: null;
  name: string;
  code: string;
  createdById: number;
  ownerId: string;
  comments: string;
  dueDate: null;
  orderItems: OrderItem[];
};

export type OrderItem = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  metadata: object;
  companyId: string;
  quantity: number;
  width: number;
  length: number;
  widthUnits: string;
  lengthUnits: string;
  description: string;
  comments: string;
  orderId: number;
  currentFile: File;
  currentFileId: number;
  filesHistory: File[];
  line: number;
  material: Material;
  materialId: number;
  position: number;
  workflowStageId: number;
  rootComment: number;
  status: string;
  receivers: any[];
  parentId: number;
};

export type File = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  metadata: object;
  originalName: string;
  uuid: string;
  type: string;
  location: string;
  path: string;
  replacedDate: string;
  preview?: File;
  previewId: number | null;
  orderItemId: number | null;
  schemeId: number;
};
